export const GOT_ALL_ARTICLES = 'GOT_ALL_ARTICLES';

export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';

export const GET_MY_ARTICLES = 'GET_MY_ARTICLES';

export const CREATED_ARTICLE = 'CREATED_ARTICLE';

export const GOT_THE_ARTICLE = 'GOT_THE_ARTICLE';

export const DELETED_THE_ARTICLE = 'DELETED_THE_ARTICLE';

export const EDITED_THE_ARTICLE = 'EDITED_THE_ARTICLE';